# Generated by Django 4.1.3 on 2022-12-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0003_alter_contact_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="birthday",
            new_name="birth",
        ),
    ]
