# Generated by Django 4.1.3 on 2022-12-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0004_rename_birthday_contact_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="birth",
            new_name="birthday",
        ),
    ]
