# Generated by Django 4.1.3 on 2022-12-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0006_rename_group_description_group_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="contact",
            name="zip_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agenda.zipcode",
            ),
        ),
    ]
