# Generated by Django 4.1.3 on 2022-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0007_remove_location_zip_code_contact_zip_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="contact/photo/nobody.png",
                upload_to="contact/photo/",
            ),
        ),
    ]
