# Generated by Django 4.1.3 on 2022-12-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0009_alter_contact_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="contact/photo/nobody.png",
                upload_to="contact/photo/",
            ),
        ),
    ]
