# Generated by Django 4.1.4 on 2023-01-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_contact_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPhone',
            new_name='PhoneJob',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='position',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='person',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='agenda/contact/photo/nobody.png', upload_to='agenda/contact/photo/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='coat',
            field=models.ImageField(blank=True, null=True, upload_to='agenda/coats/countries/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='agenda/flags/countries/'),
        ),
        migrations.AlterField(
            model_name='province',
            name='coat',
            field=models.ImageField(blank=True, null=True, upload_to='agenda/coats/provinces/'),
        ),
        migrations.AlterField(
            model_name='province',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='agenda/flags/provinces/'),
        ),
        migrations.AlterField(
            model_name='town',
            name='coat',
            field=models.ImageField(blank=True, null=True, upload_to='agenda/coats/towns/'),
        ),
        migrations.AlterField(
            model_name='town',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='agenda/flags/towns/'),
        ),
    ]
