# Generated by Django 4.1.7 on 2023-02-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
